"""Initial migration

Revision ID: 52b24aec1ef9
Revises: 
Create Date: 2025-07-16 19:12:00.935007

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b24aec1ef9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('link', sa.String(), nullable=True))
    op.add_column('site', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'online')
    op.drop_column('site', 'link')
    # ### end Alembic commands ###
