"""Adiciona relacionamento entre Group e Site com cascade

Revision ID: ed62f4c6fc01
Revises: 52b24aec1ef9
Create Date: 2025-07-16 22:39:35.360570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed62f4c6fc01'
down_revision: Union[str, Sequence[str], None] = '52b24aec1ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
